version: '3.8'

services:
  frontend:
    build:
      context: ./xeno-crm-frontend
      dockerfile: Dockerfile
    env_file:
      - ./xeno-crm-frontend/.env
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - PORT=3001
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - backend

  backend:
    build:
      context: ./xeno-crm-backend
      dockerfile: Dockerfile
    env_file:
      - ./xeno-crm-backend/.env
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/xenocrm
      - REDIS_URI=redis://redis:6380
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: 